### ISSUE TITLE
感谢分享！

### ISSUE THREAD

**Issue by renchao123** [SunAlwaysOnline/SDDB#7]

**Comment by SunAlwaysOnline** [comment]
这位同学你好，实在抱歉，目前该代码为SDDB项目的第一版，该项目我已经不再负责，由我的学妹学弟接手了。目前已经由学校申请了软件著作权，本人不拥有任何权利了。
且数据库文件中部分数据涉及学生隐私，表结构与校官网的教务系统高度相似，故不能暴露出去。
感谢您的理解！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SunAlwaysOnline/SDDB"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月9日(星期六) 晚上9:26
收件人:&nbsp;"SunAlwaysOnline/SDDB"<SDDB@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[SunAlwaysOnline/SDDB] 大佬，你好，请问可以提供一下数据库文件吗？参考学习，非常感谢大佬的分享！谢谢 (#7)
